INSERT INTO users (name, email, password_hash) VALUES
('Admin', 'admin@emekmermerantalya.com', '$2y$12$HIBBwy5EuiEbGGozBCevH.wCWRAbUOkSDIm9lOV5gaWx.5kS0RweC');

INSERT INTO settings (`key`, value) VALUES
('site_name', 'Emek Mermer Antalya'),
('phone', '+90 242 000 0000'),
('whatsapp', '+90 242 000 0000'),
('email', 'info@emekmermerantalya.com'),
('address', 'Antalya, Türkiye'),
('logo_light', 'assets/logo-light.svg'),
('logo_dark', 'assets/logo-dark.svg'),
('favicon', 'assets/favicon.svg'),
('goremedya_logo', 'assets/goremedya.svg'),
('ga_measurement_id', ''),
('ads_summary', '');

INSERT INTO sliders (title, subtitle, image_path, sort_order, is_active) VALUES
('Antalya Mermer Ustası', 'Profesyonel ölçü ve montaj', 'assets/placeholder.svg', 1, 1),
('Granit ve Kuvars Tezgah', 'Dayanıklı ve şık çözümler', 'assets/placeholder.svg', 2, 1),
('Özel Proje Uygulamaları', 'Merdiven ve dış cephe kaplama', 'assets/placeholder.svg', 3, 1);

INSERT INTO categories (name, slug, description) VALUES
('Mermer Tezgah', 'mermer-tezgah', 'Mutfak ve banyo için mermer tezgah uygulamaları'),
('Granit Tezgah', 'granit-tezgah', 'Dayanıklı granit tezgah seçenekleri'),
('Çimstone', 'cimstone', 'Kuvars esaslı çimstone modelleri');

INSERT INTO products (category_id, name, slug, description, image_path) VALUES
(1, 'Calacatta Mermer Tezgah', 'calacatta-mermer-tezgah', 'Klasik ve zarif görünüm sunan calacatta mermer tezgah.', 'assets/placeholder.svg'),
(2, 'Siyah Granit Tezgah', 'siyah-granit-tezgah', 'Yoğun kullanım için ideal, dayanıklı siyah granit.', 'assets/placeholder.svg'),
(3, 'Beyaz Çimstone Tezgah', 'beyaz-cimstone-tezgah', 'Minimal ve modern mekanlar için çimstone.', 'assets/placeholder.svg');

INSERT INTO faqs (question, answer) VALUES
('Mermer tezgah bakımı nasıl yapılır?', 'Yumuşak temizleyiciler ve nemli bezle düzenli bakım yapılmalıdır.'),
('Granit tezgah çizilir mi?', 'Granit dayanıklıdır ancak keskin darbelere karşı korunmalıdır.'),
('Çimstone fiyatları nasıl belirlenir?', 'Kalınlık, renk ve proje ölçüsüne göre fiyatlandırılır.');

INSERT INTO posts (title, slug, excerpt, content, published_at) VALUES
('Antalya Mermer Fiyatları', 'antalya-mermer-fiyatlari', 'Mermer fiyatları nasıl belirlenir, hangi detaylar maliyeti etkiler?', 'Antalyada mermer fiyatları, taşın menşei, damar yapısı, kalınlığı ve kullanılacak alanın ölçüsüne göre belirlenir. İlk adımda projeye uygun taş seçimi yapılır ve bu seçimde blok kalitesi ön plana çıkar. Damar dengesi ve renk homojenliği ne kadar yüksekse maliyet de o kadar yukarı çıkar. Bununla birlikte kesim planı ve fire oranı maliyeti belirleyen kritik bir başlıktır.\n\nUygulama alanı genişledikçe, taşın metrekare fiyatı yanında işçilik kalemleri de artar. Mutfak tezgahı, ada, backsplash ve özel kesimlerde ekstra detaylar fiyatı etkiler. Örneğin evye altı işleme, damlalık, parlatma ve kenar profili gibi detaylar ayrı bir emek gerektirir. Bu nedenle keşif yapılmadan net fiyat vermek yerine, planlı bir ölçüm ve taş seçimi süreci yürütmek gerekir.\n\nFiyatlandırmada montaj süreci de önemli bir kalemdir. Mermerin taşınması, şantiye koşulları ve montaj ekipmanları proje planına göre değerlendirilir. Antalya genelinde yapılan projelerde, ulaşım ve kurulum planlaması fiyatı değiştirebilir. Ayrıca koruyucu kimyasallar, yüzey emprenye uygulamaları ve bakım önerileri de maliyete dahil edilir.\n\nEmek Mermer Antalya olarak bütçeyi şeffaf şekilde planlarız. Proje detaylarına göre farklı seçenekler sunar, uzun ömürlü ve prestijli bir sonuç hedefleriz. Böylece fiyat, sadece bir rakam değil; kalite, işçilik ve kalıcılığın birleştiği bir değer haline gelir.', NOW()),
('Granit mi Çimstone mu', 'granit-mi-cimstone-mu', 'Granit ve çimstone arasındaki farkları ve seçim kriterlerini keşfedin.', 'Granit ve çimstone, mutfak ve banyo tezgahlarında en çok tercih edilen iki malzemedir ancak kullanım beklentisine göre farklı avantajlar sunarlar. Granit doğal bir taştır; her plaka kendi içinde benzersiz damar ve renk geçişlerine sahiptir. Yüksek ısıya dayanıklılığı ve darbelere karşı direnci ile uzun ömürlü bir seçenek sunar. Çimstone ise kuvars esaslı yapısı ile daha kontrollü bir görünüm sağlar.\n\nGranitin doğal yapısı onu daha sert kılar, bu da yoğun kullanım alanlarında avantajdır. Çizilme direnci yüksektir ancak asidik ürünlere karşı dikkatli olmak gerekir. Çimstone ise gözeneksiz yüzeyi sayesinde leke tutmaya karşı daha dirençlidir. Temizlik ve bakım kolaylığı isteyen kullanıcılar için pratik bir seçimdir. Renk seçenekleri daha geniştir ve modern mutfak tasarımlarıyla uyum yakalar.\n\nSeçim aşamasında kullanım yoğunluğu, estetik beklenti ve bütçe birlikte değerlendirilmelidir. Granit doğal doku isteyenler için güçlü bir çözümdür. Çimstone ise sade ve modern bir çizgi arayanlar için idealdir. Her iki seçenek de doğru işçilik ve kaliteli montaj ile uzun yıllar sorunsuz kullanılır. Bu nedenle sadece malzeme değil, uygulama kalitesi de önemlidir.\n\nEmek Mermer Antalya olarak proje ihtiyaçlarına göre doğru yönlendirme yaparız. Taş numuneleri, yüzey seçenekleri ve bakım ihtiyaçlarını birlikte değerlendirerek karar sürecini kolaylaştırırız. Böylece hem estetik hem de fonksiyonel açıdan en doğru seçimi yapabilirsiniz.', NOW()),
('Kuvars Tezgah Bakımı', 'kuvars-tezgah-bakimi', 'Kuvars tezgahların ilk günkü görünümünü korumak için pratik bakım önerileri.', 'Kuvars tezgahlar, yüksek dayanım ve modern görünüm sunan yüzeylerdir. Günlük temizlikte ılık su ve yumuşak bir bez kullanmak yüzeyi korur. Aşındırıcı süngerler ve yoğun kimyasallar kuvarsın parlaklığını azaltabilir. Bu nedenle pH dengeli temizlik ürünleri tercih edilmelidir. Rutin bakım ile kuvars yüzeyler uzun yıllar ilk günkü görünümünü korur.\n\nSıcak tencere ve tavalar kuvars yüzeyde ani ısı değişimleri yaratabilir. Her ne kadar kuvars dayanıklı olsa da ısı altlığı kullanmak yüzeyi korur. Kesme işlemleri için mutlaka kesme tahtası tercih edilmelidir. Yüzeyin çizilmeye karşı direnci yüksek olsa da uzun vadede bıçak izleri oluşabilir. Basit önlemler ile bu riskler minimuma iner.\n\nLeke oluşumu için hızlı müdahale önemlidir. Kahve, çay veya yağ bazlı ürünler yüzeyde bekletilmemelidir. Dökülen ürünler hızlıca silinmeli ve kuru bir bezle parlatılmalıdır. Bu alışkanlık, kuvars yüzeyin rengini ve dokusunu korur. Ayrıca yılda bir kez profesyonel bakım ile yüzey parlaklığı artırılabilir.\n\nEmek Mermer Antalya ekibi olarak kuvars tezgahlar için bakım önerilerini detaylı şekilde paylaşırız. Montaj sonrası kullanıcıya özel bakım rehberi sunarız. Böylece yüzeyiniz estetik ve fonksiyonel olarak uzun yıllar değerini korur.', NOW()),
('Mutfak Tezgahı Ölçüsü Nasıl Alınır', 'mutfak-tezgahi-olcusu-nasil-alinir', 'Mutfak tezgahı ölçüsü alırken dikkat edilmesi gereken adımlar.', 'Mutfak tezgahı ölçüsü almak, doğru bir üretim için en kritik adımdır. Ölçüm sırasında dolap hizası, duvar açıları ve tesisat çıkışları dikkatle değerlendirilmelidir. Ölçü hataları, montajda ek parça gereksinimine veya taşın yeniden kesilmesine yol açabilir. Bu nedenle ölçüm, profesyonel ekipmanlar ile yapılmalıdır.\n\nTezgah derinliği ve yükseklik standardı, ergonomi açısından önemlidir. Kullanıcı alışkanlıkları ve mutfak planına göre özel ölçüler uygulanabilir. Ada tezgahı, bar ve yemek hazırlık alanları için farklı yükseklikler tercih edilir. Ölçü sırasında bu detayların planlanması, proje sonucunu daha konforlu hale getirir.\n\nKesim planı oluşturulurken evye ve ocak yerleşimi belirlenir. Ayrıca priz çıkışları, backsplash yüksekliği ve kenar profili gibi detaylar ölçüye dahil edilir. Bu aşamada taşın damar yönü de hesaplanır. Böylece görsel bütünlük sağlanır ve uzun vadede estetik bir görünüm elde edilir.\n\nEmek Mermer Antalya ekibi ölçü sürecini projeye özel olarak planlar. Yerinde keşif yapar, kullanıcı ihtiyaçlarını dinler ve en doğru tezgah ölçüsünü çıkarır. Doğru ölçü, kaliteli işçiliğin temelini oluşturur ve kusursuz bir montajın önünü açar.', NOW()),
('Mermer mi Granit mi', 'mermer-mi-granit-mi', 'Mermer ve granit arasında karar verirken dikkat edilmesi gereken kriterler.', 'Mermer ve granit, doğal taş dünyasının en değerli seçenekleridir. Mermer, zarif damar yapısı ve yumuşak geçişleriyle estetik açıdan öne çıkar. İç mekanlarda özellikle lüks ve klasik tasarımlar için tercih edilir. Granit ise daha sert yapısı ve yoğun kullanım alanlarındaki dayanımı ile bilinir. Bu nedenle seçim, kullanım alanına göre yapılmalıdır.\n\nMermer yüzeyler düzenli bakım ister. Asidik ürünlere karşı hassastır ve leke oluşumuna dikkat edilmelidir. Granit ise daha gözeneksiz yapısı sayesinde leke tutma riski daha düşüktür. Mutfak tezgahında yoğun kullanım planlanıyorsa granit güvenli bir alternatif olabilir. Mermer ise dekoratif alanlarda benzersiz bir şıklık sağlar.\n\nRenk ve doku tercihleri de önemli bir kriterdir. Mermerde doğal damar yapısı nedeniyle her plaka benzersizdir. Granit, daha homojen bir görünüm sunar ve renk çeşitliliği fazladır. Her iki taş da doğru uygulama ile uzun ömürlü olur. Önemli olan kullanım alışkanlıkları ve bakım beklentilerini doğru analiz etmektir.\n\nEmek Mermer Antalya olarak mermer ve granit seçeneklerini numunelerle sunarız. Proje bütçesine, kullanım ihtiyacına ve estetik beklentiye göre en doğru yönlendirmeyi yaparız. Böylece hem dayanım hem de görsel kalite bakımından üst düzey bir sonuç elde edilir.', NOW()),
('Çimstone Renkleri', 'cimstone-renkleri', 'Çimstone renk seçiminde dikkat edilmesi gereken noktalar ve trendler.', 'Çimstone, kuvars esaslı yapısı ve geniş renk skalası ile modern yaşam alanlarında öne çıkar. Açık tonlar ferah bir atmosfer oluştururken, koyu tonlar daha güçlü bir karakter yaratır. Renk seçimi yapılırken mekanın ışık alma durumu ve mobilya tonları mutlaka dikkate alınmalıdır. Böylece mutfak ve banyo gibi alanlarda dengeli bir görünüm elde edilir.\n\nGri ve bej tonları, zamansız bir şıklık sunar ve farklı dekorasyon stilleriyle uyum yakalar. Beyaz ve krem tonları, minimal tasarımlar için idealdir. Mat ve parlak yüzey seçenekleri de renk algısını etkiler. Mat yüzeyler daha sakin ve modern bir görünüm sağlar, parlak yüzeyler ise ışığı yansıtarak alanı daha geniş gösterir.\n\nRenk seçimi sadece estetik değil, kullanım kolaylığı açısından da önemlidir. Açık tonlar geniş alanlarda ferahlık hissi yaratırken, koyu tonlar küçük alanlarda derinlik kazandırabilir. Leke görünürlüğü ve bakım kolaylığı da renk seçiminde değerlendirilmelidir. Doğru renk, mekanın değerini yükseltir ve uzun yıllar memnuniyet sağlar.\n\nEmek Mermer Antalya, çimstone renk kartelalarını projeye özel şekilde sunar. Numune incelemesi ile en uygun tonu belirlemenize yardımcı oluruz. Böylece mekanınızda hem trend hem de zamansız bir görünüm yakalarsınız.', NOW()),
('Banyo Tezgahı Taş Seçimi', 'banyo-tezgahi-tas-secimi', 'Banyo tezgahında doğru taş seçimi için öneriler ve kriterler.', 'Banyo tezgahı seçerken suya ve neme dayanım, bakım kolaylığı ve estetik görünüm birlikte değerlendirilmelidir. Banyo ortamı sürekli nemli olduğu için gözeneksiz yüzeyler daha avantajlıdır. Kuvars ve çimstone bu açıdan pratik çözümler sunar. Mermer ise lüks ve klasik görünüm sağlar ancak düzenli bakım ister.\n\nBanyo tezgahlarında lavabo kesimi ve kenar profili gibi detaylar kullanım konforunu etkiler. Kenarların yuvarlatılması hem güvenlik hem de görsel yumuşaklık sağlar. Renk tercihi yapılırken banyonun duvar ve zemin kaplamaları ile uyumlu tonlar seçilmelidir. Böylece bütünlük sağlayan bir tasarım elde edilir.\n\nDayanıklı bir banyo tezgahı için montaj kalitesi kritiktir. Su geçiş noktalarının doğru yalıtımı, yüzeyin uzun süre sağlıklı kalmasını sağlar. Ayrıca bakım önerileri kullanıcıya net şekilde aktarılmalıdır. Hafif temizlik ürünleri ile düzenli bakım yapılması, yüzeyin parlaklığını korur.\n\nEmek Mermer Antalya, banyo tezgahlarında hem modern hem klasik seçenekler sunar. Projeye özel taş seçimi yapar, montajı özenle uygularız. Böylece banyo alanınızda estetik ve dayanıklı bir yüzey elde edersiniz.', NOW()),
('Mermer Merdiven', 'mermer-merdiven', 'Mermer merdiven tasarımı ve uygulamasında önemli detaylar.', 'Mermer merdivenler, prestijli mekanlarda güçlü bir etki yaratır. Damar geçişleri ve doğal parlaklığı ile mermer, merdivenlerde estetik bir odak noktası olur. Ancak merdiven uygulamalarında güvenlik de en az estetik kadar önemlidir. Kaymaz yüzey işlemleri ve doğru basamak yüksekliği bu nedenle dikkatle planlanmalıdır.\n\nBasamak ölçüleri ergonomi açısından standartlara uygun olmalıdır. Rıht yüksekliği ve basamak derinliği dengeli olduğunda kullanım daha konforlu olur. Mermerin seçimi kadar montaj detayı da önem taşır. Basamak birleşim noktaları, çizgisel bir bütünlük sağlayacak şekilde planlanmalıdır.\n\nMermer merdivenlerde yüzey seçenekleri farklıdır. Parlak yüzey daha gösterişli görünürken, mat yüzey kayma riskini azaltır. Ayrıca kenar profilleri, merdivenin tasarım diline göre belirlenir. Modern çizgide düz kenarlar tercih edilirken klasik tasarımlarda daha detaylı profiller kullanılabilir.\n\nEmek Mermer Antalya, mermer merdiven projelerinde ölçüden uygulamaya kadar tüm süreci yönetir. Güvenlik standartlarına uygun çözümler üretir ve uzun ömürlü bir sonuç sunar. Böylece merdivenleriniz hem estetik hem de fonksiyonel bir değer kazanır.', NOW()),
('Dış Cephe Doğal Taş', 'dis-cephe-dogal-tas', 'Dış cephelerde doğal taş kullanımının avantajları ve uygulama detayları.', 'Dış cephede doğal taş kullanımı, yapıların değerini artıran güçlü bir tasarım seçeneğidir. Mermer, granit ve traverten gibi taşlar, dış mekan koşullarına dayanıklıdır. Doğru yüzey seçimi ile hem estetik hem de uzun ömürlü bir cephe elde edilir. Doğal taş, güneş ışığı ve yağmur gibi etkiler karşısında yüksek dayanım sağlar.\n\nUygulama öncesinde cephe sisteminin doğru şekilde hazırlanması gerekir. Taşların arka yüzeyindeki tutunma detayı ve montaj yöntemi, güvenli bir uygulama için önemlidir. Ayrıca taşın kalınlığı ve yüzey işlemine göre montaj ekipmanı belirlenir. Bu detaylar, dış cephe uygulamasının uzun yıllar sağlıklı kalmasını sağlar.\n\nRenk seçimi ve taş dizilimi de cephe karakterini belirler. Açık tonlar yapıya ferahlık ve modernlik kazandırırken, koyu tonlar daha güçlü bir görünüm sağlar. Damar geçişlerinin düzenli planlanması, cephede bütünlük oluşturur. Böylece dış cephe, binanın mimari kimliğini güçlendirir.\n\nEmek Mermer Antalya, dış cephe projelerinde uygun taş seçimi ve uygulama planı sunar. Uzman ekibimiz ile güvenli montaj gerçekleştirir, projeye özel çözümler üretiriz. Sonuç olarak yapı hem estetik hem de değer bakımından üst seviyeye çıkar.', NOW()),
('Antalya Tezgah Montaj Süreci', 'antalya-tezgah-montaj-sureci', 'Tezgah montajında keşiften teslimata kadar tüm adımlar.', 'Tezgah montaj süreci, keşif ve ölçüm ile başlar. Bu aşamada mekandaki tüm detaylar incelenir ve doğru ölçüler alınır. Ardından seçilen taşın kesim planı hazırlanır. Kesim sırasında taşın damar yönü ve estetik bütünlüğü dikkate alınır. Böylece üretim süreci hatasız ilerler.\n\nÜretim sonrası taş, montaj alanına dikkatli şekilde taşınır. Montajda birleşim noktaları, derz aralıkları ve yalıtım detayları kontrol edilir. Evye ve ocak kesimleri montaj sırasında netleştirilir ve yüzeyler hizalanır. Bu süreçte kullanılan ekipmanlar, taşın zarar görmemesi için özel olarak seçilir.\n\nMontaj tamamlandıktan sonra yüzey temizliği ve koruma uygulaması yapılır. Taşın parlaklığı ve dokusu korunur. Kullanıcıya bakım önerileri iletilir ve uzun vadeli koruma için gerekli bilgiler paylaşılır. Böylece montaj süreci sadece kurulum değil, aynı zamanda bakım bilgilendirmesi ile tamamlanır.\n\nEmek Mermer Antalya, montaj sürecini planlı ve şeffaf şekilde yönetir. Her adımda kalite kontrol yapar ve müşteri onayı ile ilerler. Bu sayede tezgahınız hem estetik hem de fonksiyonel olarak kusursuz şekilde teslim edilir.', NOW());
